# .github/workflows/deploy.yml
name: Auto-Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npx hardhat compile
      - name: Deploy to Songbird
        run: npx hardhat run scripts/deploy.js --network songbird
        env:
          PRIVATE_KEY: ${{ secrets.SONGBIRD_DEPLOYER }}
          FTSO_ADDRESS: ${{ secrets.FTSO_CONTRACT }}
      - name: Deploy to Flare
        run: npx hardhat run scripts/deploy.js --network flare
        env: 
          PRIVATE_KEY: ${{ secrets.FLARE_DEPLOYER }}
          FTSO_ADDRESS: ${{ secrets.FLARE_FTSO }}